---
- name: Install Nginx
  dnf:
    name: "{{ webserver_pkg }}"
    state: latest

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Ensure nginx is running
  systemd:
    name: "{{ webserver_pkg }}"
    state: started
    enabled: yes


